resolver: nightly-2020-02-15
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
- 'cmark-gfm-0.2.0'
- 'hslua-module-system-0.2.1'
- 'ipynb-0.1'
- 'lrucache-1.2.0.1'
- 'pandoc-2.9.1.1'
- 'pandoc-citeproc-0.17'
- 'skylighting-0.8.3.2'
- 'skylighting-core-0.8.3.2'
- HsYAML-0.2.1.0
- doctemplates-0.8
- haddock-library-1.8.0
- optparse-applicative-0.15.1.0
- pandoc-types-1.20
- regex-tdfa-1.3.1.0
- template-haskell-2.15.0.0
- texmath-0.12.0.1
- text-1.2.4.0
- parsec-3.1.14.0
- Cabal-3.0.0.0
